version: '3.7'

services:
  database:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - /Library/PostgreSQL/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - 3000:3000
    